'use strict';
const $=id=>document.getElementById(id);
const C={blue:'#255cf4',mint:'#008575',red:'#c94359',ink:'#152139',muted:'#64728a',grid:'#e3e9f3'};
const LINEAR_DATA=[{x:1,y:43},{x:2,y:47},{x:3,y:51},{x:4,y:59},{x:5,y:61},{x:6,y:68},{x:7,y:72},{x:8,y:81},{x:9,y:83},{x:10,y:91}];
const sigmoid=z=>z>=0?1/(1+Math.exp(-z)):Math.exp(z)/(1+Math.exp(z));
const mse=(w,b,data=LINEAR_DATA)=>data.reduce((s,d)=>s+(w*d.x+b-d.y)**2,0)/data.length;
function ols(data=LINEAR_DATA){const n=data.length,x=data.reduce((s,d)=>s+d.x,0)/n,y=data.reduce((s,d)=>s+d.y,0)/n;const w=data.reduce((s,d)=>s+(d.x-x)*(d.y-y),0)/data.reduce((s,d)=>s+(d.x-x)**2,0);return {w,b:y-w*x};}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function chart(id,opt={}){const svg=$(id),W=680,H=370,L=64,R=22,T=24,B=56;const {xmin=0,xmax=11,ymin=0,ymax=110,xlabel='学习时长 / 小时',ylabel='考试分数 / 分',xticks=[0,2,4,6,8,10],yticks=[0,20,40,60,80,100]}=opt;const x=v=>L+(v-xmin)/(xmax-xmin)*(W-L-R),y=v=>H-B-(v-ymin)/(ymax-ymin)*(H-T-B);let s=`<defs><clipPath id="clip-${id}"><rect x="${L}" y="${T}" width="${W-L-R}" height="${H-T-B}"/></clipPath></defs>`;for(const t of yticks)s+=`<line x1="${L}" y1="${y(t)}" x2="${W-R}" y2="${y(t)}" stroke="${C.grid}"/><text x="${L-12}" y="${y(t)+5}" text-anchor="end" font-size="13" fill="${C.muted}">${t}</text>`;for(const t of xticks)s+=`<line x1="${x(t)}" y1="${T}" x2="${x(t)}" y2="${H-B}" stroke="${C.grid}"/><text x="${x(t)}" y="${H-B+24}" text-anchor="middle" font-size="13" fill="${C.muted}">${t}</text>`;s+=`<text x="${L}" y="15" font-size="13" fill="${C.muted}">${esc(ylabel)}</text><text x="${(L+W-R)/2}" y="${H-6}" text-anchor="middle" font-size="13" fill="${C.muted}">${esc(xlabel)}</text>`;return {svg,x,y,base:s,finish:body=>svg.innerHTML=s+`<g clip-path="url(#clip-${id})">${body}</g>`,xmin,xmax,ymin,ymax};}
function pathLine(p,fn,start,end,color=C.blue,width=3){let d='';for(let i=0;i<=180;i++){const v=start+(end-start)*i/180;d+=(i?'L':'M')+p.x(v).toFixed(2)+','+p.y(fn(v)).toFixed(2);}return `<path d="${d}" fill="none" stroke="${color}" stroke-width="${width}"/>`;}
function dot(p,x,y,color,r=5){return `<circle cx="${p.x(x)}" cy="${p.y(y)}" r="${r}" fill="${color}" stroke="white" stroke-width="1.6"/>`;}
function renderLinear(exact){const w=exact?.w??+$('weight').value,b=exact?.b??+$('bias').value;$('weightOut').textContent=w.toFixed(2);$('biasOut').textContent=b.toFixed(2);$('mseOut').textContent=mse(w,b).toFixed(2);const p=chart('linearPlot');let body=pathLine(p,x=>w*x+b,0,11);for(const d of LINEAR_DATA){if($('residuals').checked)body+=`<line x1="${p.x(d.x)}" x2="${p.x(d.x)}" y1="${p.y(d.y)}" y2="${p.y(w*d.x+b)}" stroke="${C.red}" stroke-width="1.5" stroke-dasharray="4 3"/>`;body+=dot(p,d.x,d.y,C.blue);}p.finish(body);$('linearReadout').textContent=`当前 ŷ = ${w.toFixed(2)}x + ${b.toFixed(2)}；学习 6 小时的预测分数为 ${(w*6+b).toFixed(1)} 分。`+(exact?' 已显示最小二乘最优值；拖动滑块可继续比较。':'');}
let linearExact=null;
for(const id of ['weight','bias'])$(id).addEventListener('input',()=>{linearExact=null;renderLinear();});$('residuals').addEventListener('change',()=>renderLinear(linearExact));$('fitBtn').onclick=()=>{linearExact=ols();$('weight').value=linearExact.w;$('bias').value=linearExact.b;renderLinear(linearExact);};$('linearReset').onclick=()=>{$('weight').value=5;$('bias').value=30;linearExact=null;renderLinear();};renderLinear();
let leftSeconds=1080,timerHandle=null,lastTick=0;
function renderClock(){const m=Math.floor(leftSeconds/60),s=leftSeconds%60;$('clock').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('timerBtn').setAttribute('aria-label',`${timerHandle?'暂停':'开始'}汇报计时，剩余${m}分${s}秒`);}
$('timerBtn').onclick=()=>{if(timerHandle){clearInterval(timerHandle);timerHandle=null;}else{lastTick=Date.now();timerHandle=setInterval(()=>{const now=Date.now(),elapsed=Math.floor((now-lastTick)/1000);if(elapsed){leftSeconds=Math.max(0,leftSeconds-elapsed);lastTick+=elapsed*1000;renderClock();}if(!leftSeconds){clearInterval(timerHandle);timerHandle=null;$('timerBtn').style.background=C.red;renderClock();}},250);}renderClock();};$('timerReset').onclick=()=>{clearInterval(timerHandle);timerHandle=null;leftSeconds=1080;$('timerBtn').style.background='';renderClock();};$('modeBtn').onclick=()=>{const on=document.body.classList.toggle('talk-mode');$('modeBtn').textContent=on?'返回学习模式':'进入汇报模式';$('modeBtn').setAttribute('aria-pressed',String(on));};
const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){document.querySelectorAll('.sidebar nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id));}},{rootMargin:'-15% 0px -65% 0px'});document.querySelectorAll('main section').forEach(s=>observer.observe(s));
let training={w:0,b:0,step:0,history:[mse(0,0)],running:null,stopped:false};
function stopTraining(){if(training.running)clearInterval(training.running);training.running=null;$('trainBtn').textContent='播放训练';}
function renderTraining(){const g=training,last=g.history.at(-1);$('iteration').textContent=g.step;$('descentMse').textContent=last<1e5?last.toFixed(2):last.toExponential(2);$('descentParams').textContent=`w = ${g.w.toFixed(3)}，b = ${g.b.toFixed(3)}`;const xmax=Math.max(30,g.step),top=Math.max(4,Math.ceil(Math.log10(Math.max(...g.history)+1))),yticks=Array.from({length:5},(_,i)=>+(top*i/4).toFixed(1));const p=chart('descentPlot',{xmin:0,xmax,ymin:0,ymax:top,xlabel:'迭代次数',ylabel:'log₁₀(1 + MSE)',xticks:[0,Math.round(xmax/4),Math.round(xmax/2),Math.round(xmax*3/4),xmax],yticks});let d='';g.history.forEach((v,i)=>d+=(i?'L':'M')+p.x(i)+','+p.y(Math.log10(v+1)));p.finish(`<path d="${d}" fill="none" stroke="${C.blue}" stroke-width="3"/>`+dot(p,g.step,Math.log10(last+1),last>g.history[0]?C.red:C.blue,6));}
function trainStep(){const g=training;if(g.stopped)return;const alpha=+$('learningRate').value;let dw=0,db=0;for(const d of LINEAR_DATA){const e=g.w*d.x+g.b-d.y;dw+=2*e*d.x/LINEAR_DATA.length;db+=2*e/LINEAR_DATA.length;}const nw=g.w-alpha*dw,nb=g.b-alpha*db;g.w=nw;g.b=nb;g.step++;g.history.push(mse(nw,nb));if(!Number.isFinite(g.history.at(-1))||g.history.at(-1)>1e12){g.stopped=true;stopTraining();$('trainStatus').textContent='误差快速增大，已停止演示。学习率过大使这次训练发散，换小一些再试。';}else if(g.step>=240){g.stopped=true;stopTraining();$('trainStatus').textContent='已演示 240 步。误差下降不代表已经最优，也不代表在新数据上表现好。';}else $('trainStatus').textContent=g.history.at(-1)>g.history[0]?'损失正在增大：步子可能过大。':'损失随更新下降，继续观察变化是否趋缓。';$('trainBtn').disabled=g.stopped;$('stepBtn').disabled=g.stopped;renderTraining();}
function resetTraining(){stopTraining();training={w:0,b:0,step:0,history:[mse(0,0)],running:null,stopped:false};$('trainBtn').disabled=false;$('stepBtn').disabled=false;$('trainStatus').textContent='从同一组初始参数重新开始，便于比较学习率。';renderTraining();}
$('trainBtn').onclick=()=>{if(training.running)stopTraining();else{training.running=setInterval(trainStep,80);$('trainBtn').textContent='暂停训练';}};$('stepBtn').onclick=()=>{stopTraining();trainStep();};$('trainReset').onclick=resetTraining;$('learningRate').onchange=resetTraining;renderTraining();
function renderSigmoid(){const z=+$('zValue').value,prob=sigmoid(z);$('zOut').textContent=z.toFixed(1);$('probOut').textContent=(100*prob).toFixed(1)+'%';$('sigmoidReadout').textContent=`p = σ(${z.toFixed(1)}) = ${prob.toFixed(4)}`;const p=chart('sigmoidPlot',{xmin:-6,xmax:6,ymin:0,ymax:1,xlabel:'线性得分 z',ylabel:'正类概率 p',xticks:[-6,-4,-2,0,2,4,6],yticks:[0,.25,.5,.75,1]});p.finish(pathLine(p,sigmoid,-6,6,C.mint)+`<path d="M${p.x(z)},${p.y(0)}L${p.x(z)},${p.y(prob)}L${p.x(-6)},${p.y(prob)}" fill="none" stroke="${C.mint}" stroke-dasharray="5 4"/>`+dot(p,z,prob,C.mint,7));}
$('zValue').oninput=renderSigmoid;document.querySelectorAll('[data-z]').forEach(b=>b.onclick=()=>{$('zValue').value=b.dataset.z;renderSigmoid();});renderSigmoid();
const crossEntropy=(p,y)=>-(y*Math.log(p)+(1-y)*Math.log(1-p));
function renderLoss(){const actual=+$('trueLabel').value,prob=+$('lossProb').value,loss=crossEntropy(prob,actual);$('lossProbOut').textContent=prob.toFixed(2);$('lossOut').textContent=loss.toFixed(3);$('lossReadout').textContent=`实际 y = ${actual}，为真实类别分配 ${(100*(actual?prob:1-prob)).toFixed(0)}% 概率。`;const p=chart('lossPlot',{xmin:0,xmax:1,ymin:0,ymax:5,xlabel:'预测正类概率 p',ylabel:'单样本交叉熵',xticks:[0,.2,.4,.6,.8,1],yticks:[0,1,2,3,4,5]});p.finish(pathLine(p,x=>crossEntropy(x,actual),.01,.99,C.mint)+dot(p,prob,loss,C.red,7));}
$('trueLabel').onchange=renderLoss;$('lossProb').oninput=renderLoss;renderLoss();
const CLASS_DATA=[{p:.08,y:0},{p:.16,y:0},{p:.24,y:1},{p:.32,y:0},{p:.41,y:1},{p:.48,y:0},{p:.56,y:1},{p:.64,y:0},{p:.71,y:1},{p:.79,y:1},{p:.87,y:0},{p:.94,y:1}];
function confusion(threshold){const out={tp:0,fn:0,fp:0,tn:0};for(const d of CLASS_DATA){const predicted=d.p>=threshold?1:0;out[d.y?(predicted?'tp':'fn'):(predicted?'fp':'tn')]++;}return out;}
function diamond(p,x,y,color,size=6){const cx=p.x(x),cy=p.y(y);return `<path d="M${cx},${cy-size}L${cx+size},${cy}L${cx},${cy+size}L${cx-size},${cy}Z" fill="${color}" stroke="white" stroke-width="1.5"/>`;}
const ratio=(a,b)=>b?`${(a/b*100).toFixed(1)}%`:'—';
function renderThreshold(){const t=+$('thresholdValue').value,m=confusion(t);$('thresholdOut').textContent=t.toFixed(2);for(const k of Object.keys(m))$(k).textContent=m[k];$('accuracy').textContent=ratio(m.tp+m.tn,CLASS_DATA.length);$('precision').textContent=ratio(m.tp,m.tp+m.fp);$('recall').textContent=ratio(m.tp,m.tp+m.fn);$('fixedLoss').textContent=(CLASS_DATA.reduce((s,d)=>s+crossEntropy(d.p,d.y),0)/CLASS_DATA.length).toFixed(3);$('thresholdReadout').textContent=`预测通过 ${m.tp+m.fp} 人，其中 ${m.fp} 人实际未通过；漏掉 ${m.fn} 位实际通过者。`+(m.tp+m.fp===0?' 没有预测正类，Precision 分母为 0，显示“—”。':'');const p=chart('thresholdPlot',{xmin:.3,xmax:12.7,ymin:0,ymax:1,xlabel:'模拟同学编号',ylabel:'固定的正类概率 p',xticks:[1,2,3,4,5,6,7,8,9,10,11,12],yticks:[0,.25,.5,.75,1]});let body=`<rect x="${p.x(.3)}" y="${p.y(1)}" width="${p.x(12.7)-p.x(.3)}" height="${p.y(t)-p.y(1)}" fill="#e6f6ee"/><line x1="${p.x(.3)}" y1="${p.y(t)}" x2="${p.x(12.7)}" y2="${p.y(t)}" stroke="${C.red}" stroke-width="2" stroke-dasharray="6 4"/>`;CLASS_DATA.forEach((d,i)=>{body+=`<line x1="${p.x(i+1)}" x2="${p.x(i+1)}" y1="${p.y(0)}" y2="${p.y(d.p)}" stroke="#cad5e6" stroke-width="2"/>`;if((d.p>=t?1:0)!==d.y)body+=`<circle cx="${p.x(i+1)}" cy="${p.y(d.p)}" r="11" fill="none" stroke="${C.red}" stroke-width="1.5"/>`;body+=d.y?dot(p,i+1,d.p,C.mint,6):diamond(p,i+1,d.p,C.blue,7);});p.finish(body);}
$('thresholdValue').oninput=renderThreshold;document.querySelectorAll('[data-threshold]').forEach(b=>b.onclick=()=>{$('thresholdValue').value=b.dataset.threshold;renderThreshold();});renderThreshold();
const BOUNDARY_DATA=[[-2,-1.6,0],[-1.7,.4,0],[-1.4,-.3,0],[-.5,-1.5,0],[.4,-1.4,0],[1.5,-1.4,0],[-1.2,1.8,1],[-.3,.9,1],[.5,.5,1],[1.4,.3,1],[1.8,1.6,1],[.8,-.3,1]];
function positivePolygon(w1,w2,b){const square=[[-2.5,-2.5],[2.5,-2.5],[2.5,2.5],[-2.5,2.5]],out=[];for(let i=0;i<4;i++){const a=square[i],c=square[(i+1)%4],va=w1*a[0]+w2*a[1]+b,vc=w1*c[0]+w2*c[1]+b;if(va>=0)out.push(a);if((va>=0)!==(vc>=0)){const f=va/(va-vc);out.push([a[0]+f*(c[0]-a[0]),a[1]+f*(c[1]-a[1])]);}}return out;}
function renderBoundary(){const w1=+$('w1').value,w2=+$('w2').value,b=+$('b2').value;for(const [id,v] of [['w1Out',w1],['w2Out',w2],['b2Out',b]])$(id).textContent=v.toFixed(1);const p=chart('boundaryPlot',{xmin:-2.5,xmax:2.5,ymin:-2.5,ymax:2.5,xlabel:'标准化学习时长 x₁',ylabel:'标准化练习完成量 x₂',xticks:[-2,-1,0,1,2],yticks:[-2,-1,0,1,2]});const poly=positivePolygon(w1,w2,b);let body=`<rect x="${p.x(-2.5)}" y="${p.y(2.5)}" width="${p.x(2.5)-p.x(-2.5)}" height="${p.y(-2.5)-p.y(2.5)}" fill="#255cf4" fill-opacity=".06"/>`;if(poly.length)body+=`<polygon points="${poly.map(q=>p.x(q[0])+','+p.y(q[1])).join(' ')}" fill="#008575" fill-opacity=".16"/>`;if(Math.abs(w2)>1e-12)body+=pathLine(p,x=>-(w1*x+b)/w2,-2.5,2.5,C.ink,2.5);else if(Math.abs(w1)>1e-12){const x=-b/w1;body+=`<line x1="${p.x(x)}" x2="${p.x(x)}" y1="${p.y(-2.5)}" y2="${p.y(2.5)}" stroke="${C.ink}" stroke-width="2.5"/>`;}let wrong=0;for(const [x,y,label] of BOUNDARY_DATA){if((w1*x+w2*y+b>=0?1:0)!==label){wrong++;body+=`<circle cx="${p.x(x)}" cy="${p.y(y)}" r="10" fill="none" stroke="${C.red}" stroke-width="1.5"/>`;}body+=label?dot(p,x,y,C.mint,6):diamond(p,x,y,C.blue,7);}p.finish(body);$('boundaryReadout').textContent=(w1===0&&w2===0?`所有位置的概率都是 ${sigmoid(b).toFixed(3)}，没有普通分割直线。`:`边界：${w1.toFixed(1)}x₁ + ${w2.toFixed(1)}x₂ + ${b.toFixed(1)} = 0。`)+` 模拟样本误分类 ${wrong}/12。`;}
for(const id of ['w1','w2','b2'])$(id).oninput=renderBoundary;$('boundaryReset').onclick=()=>{$('w1').value=1;$('w2').value=1;$('b2').value=0;renderBoundary();};renderBoundary();
const QUIZZES=[{q:'1. 单个样本的预测误差从 2 分变成 4 分，它对平方损失的贡献变为原来的几倍？',a:['2 倍','4 倍','不变'],correct:1,why:'4²/2² = 4。平方损失会更强地惩罚较大的误差。'}, {q:'2. 模型固定，只把分类阈值从 0.5 改成 0.7，哪些数值一定保持不变？',a:['每个样本的预测概率','混淆矩阵','召回率'],correct:0,why:'阈值改变决策规则，模型的参数和预测概率没有变化，平均 LogLoss 也保持不变。'}, {q:'3. 在二维原始特征上，标准逻辑回归的 Sigmoid 是曲线，因此决策边界一定弯曲。',a:['正确','错误'],correct:1,why:'阈值0.5下边界满足 w₁x₁ + w₂x₂ + b = 0。非零权重时是直线，S形的是概率对线性得分的映射。'}, {q:'4. 测试集上的 R² = −0.2 说明什么？',a:['程序必定算错了','比该评价集均值基线更差','准确率是 −20%'],correct:1,why:'R² 可以为负，它不是分类准确率。预测残差平方和大于均值基线的平方和时就会出现负值。'}, {q:'5. 哪个预处理流程正确？',a:['全体标准化，再划分','先划分，仅用训练集拟合标准化'],correct:1,why:'先划分，再用训练集fit预处理，验证集和测试集只transform，避免信息泄漏。'}];
$('quizList').innerHTML=QUIZZES.map((q,i)=>`<article class="quiz-card"><h3>${esc(q.q)}</h3><div class="quiz-options">${q.a.map((a,j)=>`<button data-quiz="${i}" data-answer="${j}">${esc(a)}</button>`).join('')}</div><p class="feedback" id="feedback${i}" aria-live="polite">选择答案后查看解析。</p></article>`).join('');document.querySelectorAll('[data-quiz]').forEach(b=>b.onclick=()=>{const i=+b.dataset.quiz,j=+b.dataset.answer,q=QUIZZES[i];document.querySelectorAll(`[data-quiz="${i}"]`).forEach(x=>x.classList.toggle('chosen',x===b));$('feedback'+i).textContent=(j===q.correct?'回答正确。':'再想一想。')+q.why;$('feedback'+i).style.color=j===q.correct?C.mint:C.red;});

// Optional standard WebMCP surface; the full page also works in browsers without it.
const demoContext=document.modelContext??navigator.modelContext;
if(demoContext?.registerTool){
  const lifecycle=new AbortController();
  try { Promise.resolve(demoContext.registerTool({name:'set_regression_demo',title:'设置回归教学演示',annotations:{readOnlyHint:false,untrustedContentHint:false},description:'设置本地教学图的参数并返回观察值。只改变网页演示状态，不保存或发送数据。',inputSchema:{type:'object',properties:{demo:{type:'string',enum:['linear','sigmoid','threshold','boundary']},w:{type:'number',minimum:-2,maximum:12},b:{type:'number',minimum:-3,maximum:70},z:{type:'number',minimum:-6,maximum:6},threshold:{type:'number',minimum:0,maximum:1},w1:{type:'number',minimum:-3,maximum:3},w2:{type:'number',minimum:-3,maximum:3}},required:['demo'],additionalProperties:false},execute:async(args)=>{
    if(!args||!['linear','sigmoid','threshold','boundary'].includes(args.demo))throw new Error('请选择有效的教学实验');
    const allowed={linear:{w:[-2,12],b:[0,70]},sigmoid:{z:[-6,6]},threshold:{threshold:[0,1]},boundary:{w1:[-3,3],w2:[-3,3],b:[-3,3]}}[args.demo];
    for(const [key,v] of Object.entries(args)){if(key==='demo')continue;const r=allowed[key];if(!r||typeof v!=='number'||!Number.isFinite(v)||v<r[0]||v>r[1])throw new Error('参数类型或范围无效：'+key);}
    const put=(id,v)=>{if(v!==undefined)$(id).value=v;};let result;
    if(args.demo==='linear'){put('weight',args.w,-2,12);put('bias',args.b,0,70);linearExact=null;renderLinear();result=$('linearReadout').textContent+' MSE='+$('mseOut').textContent;}
    else if(args.demo==='sigmoid'){put('zValue',args.z,-6,6);renderSigmoid();result=$('sigmoidReadout').textContent;}
    else if(args.demo==='threshold'){put('thresholdValue',args.threshold,0,1);renderThreshold();result=$('thresholdReadout').textContent;}
    else {put('w1',args.w1,-3,3);put('w2',args.w2,-3,3);put('b2',args.b,-3,3);renderBoundary();result=$('boundaryReadout').textContent;}
    return {content:[{type:'text',text:result}]};}}, {signal:lifecycle.signal})).catch(()=>{}); } catch {}
  window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
